name: phoenix_network_core
description: The core data layer framework for Phoenix Architecture, providing robust networking, caching, and data persistence patterns.
version: 0.0.1
homepage: https://github.com/your_username/phoenix_network_core

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.3.3
  get_it: ^7.6.4
  provider: ^6.0.5
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  # 替换下面这行
  # dio_http_cache: ^0.3.0  <- 删除这行
  dio_cache_interceptor: ^3.4.4 # <- 添加这行，这是 Dio v5 兼容的缓存库
  dio_smart_retry: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0